# Generated by Django 5.0.6 on 2024-06-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('unidade_medida', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.entrega')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.doacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.produto')),
            ],
        ),
    ]
