# Generated by Django 5.0.4 on 2024-06-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega_item',
            name='entrega',
        ),
    ]
